//+------------------------------------------------------------------+
//|                                                PriceAction_EA.mq5 |
//|                                       Generated by Assistant AI  |
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "Your Name"
#property link      ""
#property version   "1.00"

// 输入参数
input double LotSize = 0.1;                    // 交易手数
input int LookbackBars = 50;                    // 用于判断新低/新高的回顾K线数量
input int EntryConfirmBars = 4;                  // 入场确认需要的K线数量（含触发K线）
input int ExitConfirmBars = 3;                    // 出场确认需要的K线数量（含触发K线）
input double MinPriceRange = 2000.0;               // 最小价格波动范围（点数，XAUUSD 20美元=2000点）
input bool UseMinRange = true;                    // 是否启用最小波动范围过滤
input int MagicNumber = 202503;                   // EA唯一标识
input bool CloseOnOppositeSignal = false;          // 出现反向信号时是否平仓

// 全局变量
int handle;
datetime lastBarTime = 0;

//+------------------------------------------------------------------+
//| 初始化函数                                                       |
//+------------------------------------------------------------------+
int OnInit() {
   // 检查输入参数有效性
   if(LotSize <= 0) {
      Print("错误：交易手数必须大于0");
      return(INIT_PARAMETERS_INCORRECT);
   }
   
   if(LookbackBars < EntryConfirmBars + 5) {
      Print("警告：回顾K线数可能过小，建议大于", EntryConfirmBars + 10);
   }
   
   lastBarTime = iTime(_Symbol, _Period, 0);
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| 反初始化函数                                                     |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   // 清理工作
}

//+------------------------------------------------------------------+
//| Tick处理函数                                                     |
//+------------------------------------------------------------------+
void OnTick() {
   // 只在新的K线开盘时执行（避免同一根K线重复触发）
   datetime currentBarTime = iTime(_Symbol, _Period, 0);
   if(currentBarTime == lastBarTime) {
      return;
   }
   lastBarTime = currentBarTime;
   
   // 获取K线数据
   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   int copied = CopyRates(_Symbol, _Period, 0, LookbackBars + EntryConfirmBars + 5, rates);
   if(copied < LookbackBars + EntryConfirmBars) {
      Print("数据不足");
      return;
   }
   
   // 检查持仓
   bool hasBuy = false, hasSell = false;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket)) {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {
            if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) hasBuy = true;
            if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_SELL) hasSell = true;
         }
      }
   }
   
   // --- 入场检查 ---
   // 做多入场
   if(!hasBuy && CheckBuyEntry(rates)) {
      OpenOrder(ORDER_TYPE_BUY);
   }
   
   // 做空入场
   if(!hasSell && CheckSellEntry(rates)) {
      OpenOrder(ORDER_TYPE_SELL);
   }
   
   // --- 出场检查 ---
   if(hasBuy) {
      if(CheckBuyExit(rates)) {
         ClosePositions(POSITION_TYPE_BUY);
      } else if(CloseOnOppositeSignal && CheckSellEntry(rates)) {
         // 如果启用反向信号平仓，且出现做空信号，则平多单
         ClosePositions(POSITION_TYPE_BUY);
      }
   }
   
   if(hasSell) {
      if(CheckSellExit(rates)) {
         ClosePositions(POSITION_TYPE_SELL);
      } else if(CloseOnOppositeSignal && CheckBuyEntry(rates)) {
         // 如果启用反向信号平仓，且出现做多信号，则平空单
         ClosePositions(POSITION_TYPE_SELL);
      }
   }
}

//+------------------------------------------------------------------+
//| 检查做多入场条件                                                 |
//+------------------------------------------------------------------+
bool CheckBuyEntry(MqlRates &rates[]) {
   // 从最新的K线开始检查（索引0是最新K线，即刚收盘的那根）
   // 我们需要找到最近的一根“新低K线”，并检查之后连续4根（含新低K线）的条件
   
   int totalBars = ArraySize(rates);
   for(int i = 1; i < totalBars - EntryConfirmBars; i++) {
      // 检查rates[i]是否是“新低K线”
      bool isNewLow = true;
      double currentLow = rates[i].low;
      
      // 与前LookbackBars根K线比较（排除自己）
      for(int j = i + 1; j <= i + LookbackBars && j < totalBars; j++) {
         if(rates[j].low <= currentLow) {
            isNewLow = false;
            break;
         }
      }
      
      if(!isNewLow) continue;
      
      // 检查价格波动范围是否满足最小要求
      if(UseMinRange) {
         double priceRange = rates[i].high - rates[i].low;
         if(priceRange < MinPriceRange * _Point) {
            continue; // 波动太小，不符合
         }
      }
      
      // 检查后续K线是否都不低于这个新低
      bool confirm = true;
      double lowestPrice = currentLow;
      for(int k = i - 1; k >= i - EntryConfirmBars + 1; k--) {
         if(k < 0) {
            confirm = false;
            break;
         }
         if(rates[k].low < lowestPrice) {
            confirm = false;
            break;
         }
      }
      
      if(confirm) {
         // 找到符合条件的入场信号
         // 注意：我们在新K线开盘时检查，此时rates[0]是上一根收盘的K线
         // 如果入场条件在更早的K线满足，但我们还没入场，应该在这里检查是否已经入场过了
         // 简单起见，这里只返回最近一个符合条件的信号
         return true;
      }
   }
   
   return false;
}

//+------------------------------------------------------------------+
//| 检查做空入场条件                                                 |
//+------------------------------------------------------------------+
bool CheckSellEntry(MqlRates &rates[]) {
   int totalBars = ArraySize(rates);
   for(int i = 1; i < totalBars - EntryConfirmBars; i++) {
      // 检查rates[i]是否是“新高K线”
      bool isNewHigh = true;
      double currentHigh = rates[i].high;
      
      // 与前LookbackBars根K线比较（排除自己）
      for(int j = i + 1; j <= i + LookbackBars && j < totalBars; j++) {
         if(rates[j].high >= currentHigh) {
            isNewHigh = false;
            break;
         }
      }
      
      if(!isNewHigh) continue;
      
      // 检查价格波动范围是否满足最小要求
      if(UseMinRange) {
         double priceRange = rates[i].high - rates[i].low;
         if(priceRange < MinPriceRange * _Point) {
            continue;
         }
      }
      
      // 检查后续K线是否都不高于这个新高
      bool confirm = true;
      double highestPrice = currentHigh;
      for(int k = i - 1; k >= i - EntryConfirmBars + 1; k--) {
         if(k < 0) {
            confirm = false;
            break;
         }
         if(rates[k].high > highestPrice) {
            confirm = false;
            break;
         }
      }
      
      if(confirm) {
         return true;
      }
   }
   
   return false;
}

//+------------------------------------------------------------------+
//| 检查多单出场条件                                                 |
//+------------------------------------------------------------------+
bool CheckBuyExit(MqlRates &rates[]) {
   // 出场逻辑：出现新的新低K线，且之后3根K线的最低价不低于新低K线的最低价，
   // 并且第4根K线开盘价 >= 第3根K线收盘价
   
   int totalBars = ArraySize(rates);
   for(int i = 1; i < totalBars - ExitConfirmBars - 1; i++) {
      // 检查rates[i]是否是“新低K线”
      bool isNewLow = true;
      double currentLow = rates[i].low;
      
      for(int j = i + 1; j <= i + LookbackBars && j < totalBars; j++) {
         if(rates[j].low <= currentLow) {
            isNewLow = false;
            break;
         }
      }
      
      if(!isNewLow) continue;
      
      // 检查后续ExitConfirmBars根K线是否都不低于这个新低
      bool confirm = true;
      for(int k = i - 1; k >= i - ExitConfirmBars + 1; k--) {
         if(k < 0) {
            confirm = false;
            break;
         }
         if(rates[k].low < currentLow) {
            confirm = false;
            break;
         }
      }
      
      if(confirm) {
         // 检查第4根K线开盘价是否 >= 第3根K线收盘价
         // 第3根K线是 rates[i - ExitConfirmBars + 1]? 注意索引：
         // 假设i=5是新高K线，ExitConfirmBars=3，那么需要检查的K线是索引4、3、2（共3根）
         // 第3根K线是索引2，第4根K线是索引1（最新收盘的K线）
         int thirdBarIndex = i - ExitConfirmBars + 1;
         int fourthBarIndex = thirdBarIndex - 1;
         
         if(thirdBarIndex >= 0 && fourthBarIndex >= 0) {
            double thirdClose = rates[thirdBarIndex].close;
            double fourthOpen = rates[fourthBarIndex].open;
            
            if(fourthOpen >= thirdClose) {
               return true; // 满足出场条件
            }
         }
      }
   }
   
   return false;
}

//+------------------------------------------------------------------+
//| 检查空单出场条件                                                 |
//+------------------------------------------------------------------+
bool CheckSellExit(MqlRates &rates[]) {
   int totalBars = ArraySize(rates);
   for(int i = 1; i < totalBars - ExitConfirmBars - 1; i++) {
      // 检查rates[i]是否是“新高K线”
      bool isNewHigh = true;
      double currentHigh = rates[i].high;
      
      for(int j = i + 1; j <= i + LookbackBars && j < totalBars; j++) {
         if(rates[j].high >= currentHigh) {
            isNewHigh = false;
            break;
         }
      }
      
      if(!isNewHigh) continue;
      
      // 检查后续ExitConfirmBars根K线是否都不高于这个新高
      bool confirm = true;
      for(int k = i - 1; k >= i - ExitConfirmBars + 1; k--) {
         if(k < 0) {
            confirm = false;
            break;
         }
         if(rates[k].high > currentHigh) {
            confirm = false;
            break;
         }
      }
      
      if(confirm) {
         // 检查第4根K线开盘价是否 <= 第3根K线收盘价
         int thirdBarIndex = i - ExitConfirmBars + 1;
         int fourthBarIndex = thirdBarIndex - 1;
         
         if(thirdBarIndex >= 0 && fourthBarIndex >= 0) {
            double thirdClose = rates[thirdBarIndex].close;
            double fourthOpen = rates[fourthBarIndex].open;
            
            if(fourthOpen <= thirdClose) {
               return true;
            }
         }
      }
   }
   
   return false;
}

//+------------------------------------------------------------------+
//| 开单函数                                                         |
//+------------------------------------------------------------------+
void OpenOrder(ENUM_ORDER_TYPE orderType) {
   MqlTradeRequest request = {};
   MqlTradeResult result = {};
   
   double price = (orderType == ORDER_TYPE_BUY) ? 
                  SymbolInfoDouble(_Symbol, SYMBOL_ASK) : 
                  SymbolInfoDouble(_Symbol, SYMBOL_BID);
   
   request.action = TRADE_ACTION_DEAL;
   request.symbol = _Symbol;
   request.volume = LotSize;
   request.type = orderType;
   request.price = price;
   request.deviation = 10;
   request.magic = MagicNumber;
   request.type_filling = ORDER_FILLING_FOK;
   
   if(!OrderSend(request, result)) {
      Print("开单失败：", result.retcode, " - ", TradeServerReturnCodeDescription(result.retcode));
   } else {
      Print("开单成功，订单号：", result.order);
   }
}

//+------------------------------------------------------------------+
//| 平仓函数                                                         |
//+------------------------------------------------------------------+
void ClosePositions(ENUM_POSITION_TYPE posType) {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket)) {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && 
            PositionGetInteger(POSITION_MAGIC) == MagicNumber &&
            PositionGetInteger(POSITION_TYPE) == posType) {
            
            MqlTradeRequest request = {};
            MqlTradeResult result = {};
            
            request.action = TRADE_ACTION_DEAL;
            request.symbol = _Symbol;
            request.volume = PositionGetDouble(POSITION_VOLUME);
            request.type = (posType == POSITION_TYPE_BUY) ? ORDER_TYPE_SELL : ORDER_TYPE_BUY;
            request.position = ticket;
            request.price = (posType == POSITION_TYPE_BUY) ? 
                            SymbolInfoDouble(_Symbol, SYMBOL_BID) : 
                            SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            request.deviation = 10;
            request.magic = MagicNumber;
            
            if(!OrderSend(request, result)) {
               Print("平仓失败：", result.retcode, " - ", TradeServerReturnCodeDescription(result.retcode));
            } else {
               Print("平仓成功，订单号：", result.order);
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| 获取服务器返回码说明                                             |
//+------------------------------------------------------------------+
string TradeServerReturnCodeDescription(int code) {
   switch(code) {
      case 10004: return "订单被服务器拒绝";
      case 10006: return "请求被服务器拒绝";
      case 10007: return "请求超时";
      case 10008: return "无效请求";
      case 10009: return "无效交易量";
      case 10010: return "无效价格";
      case 10011: return "无效止损";
      case 10012: return "无效止盈";
      case 10013: return "市场已关闭";
      case 10014: return "无足够资金";
      case 10015: return "订单价格已变";
      case 10016: return "存在挂单";
      case 10017: return "限价订单";
      case 10018: return "订单已锁定";
      case 10019: return "订单已执行";
      default: return "未知错误";
   }
}
//+------------------------------------------------------------------+